language: node_js
node_js:
- '0.10'
script:
- npm run build
after_success:
- build/deploy.sh
notifications:
  email: false
  slack:
    secure: KMZdV6pnRPqcqxeZ0bHBM/4GXhBiJUPmONHWlrnCYaKnJyOvpBNHeL8ubdIKkYgc5X9LsHG7k5LGyfiRbmt/o1majMje/+Gadorb9DRJQ15ZbtPBllwOeLiFnr6WykSf7UbDnY5XgmD/eNRwU1KYSC+PvAJ53LlQy53BvZc7hcU=
